server:
  port: 8081


#日志
logging:
  config: classpath:logconfig/logback.xml
  path: /home/sinbad/work/workspace/logs/web-api-demo
  level:
    org.springframework.web: trace

spring:
  application:
    name: webApi


  #热部署 重启 #热部署扫包位置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java