server:
  port: 8082

spring:
  application:
    name: config-client
  profiles:
    active: test



data:
  env: NaN
  datasource:
    datasource-demo:
      username: NaN
      password: NaN


#监控管理
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"